giuspen/cherrytree

.gitignore, modules/exports.py
Hi Giuspen
Thanks for writing CherryTree, I am starting to use it as a lab book. I really like it for this as I can give others read access to an HTML export without them needing to install anything.
One thing that was worrying though was any embedded files were not exported as part of the HTML export. I have added this functionality in my first commit. I only do it for the HTML node export, not for the HTML selection export, because as far as I can see this is only for copying to the clipboard (am I correct on this?).
I am also thinking of extending the command line functionality to allow HTML export so I can automate it.
Julian
=> Export to HTML now exports embedded files.

cherrytree, modules/core.py, modules/exports.py, modules/main.py
Hi Giuseppe (sorry for misspelling your name before!)
As I said before I was planning to make HTML exporting possible from the command line, so I can automate the export. I have managed this. I just create a "Ghost window" for cherry tree which does all the initialisation, but never shows the window, then I run the full export for all nodes. I have updated the command line options, to allow an output option and an option for the export. When starting it doesn't check for a D-Bus session, because then it can't export if the program is open.
I made on other change to the HTML export for the normal graphical method. Now when the export folder already exists it numbers them
file.ctb_HTML
file.ctb_HTML002
file.ctb_HTML003
file.ctb_HTML004
instead of
file.ctb_HTML
file.ctb_HTML2
file.ctb_HTML22 …
=> Command line HTML export

glade/styles.css, modules/exports.py
Hi Giuseppe,
A couple of bug fixes for the new style of HTML export from Emily V:
* Tree needs `</ol>` tags after last node in list.
* Tree missing `</a>` tag from top level nodes.
* Final `</div>` tag missing
* Width didn't include margin so text extended 380px to right of screen. Fixed in css by changing margin to padding and extending the bounding box to include padding.
I have also added the name of the current node to top of the page.
=> Fixed HTML unclosed tags and text overlapping edge of page.

modules/imports.py
When importing from a BasKet folder the cross references are missing. Since there is no cross reference feature in cherrytree yet, this simple fix just adds a text in the node like "cross reference: {title-of-basket-cross-reference}". i18n is not supported yet.
=> possible fix for #73

locale/de.po
The German translation had the same translation for cut/copy/paste plain text, which is fixed by this PR.
=> Fix German translation

modules/config.py, modules/core.py
This adds an unique option to the settings/config which drives GtkSourceView/GtkTextView.set_pixels_above_lines and set_pixels_below_lines.
Solves one TODO on your list and this request: [www.giuspen.com/topic/line-height-setting/](http://www.giuspen.com/topic/line-height-setting/)
A proper implementation could be relative line-height based on the font height, but I felt that this basic implementation works well enough.
**Please note**: This adds an offset to the line numbers (which seems to be an SourceView issue as the above spacing is not being added to the numbers/gutter), but the numbers still match.
The only alternative I see is only adding the space below, but then the line highlight would be off, which I personally find more distracting.
=> Basic implementation of line height settings.

modules/config.py, modules/core.py
Embedded file icon and its tooltip will remain visible, it's name can be hidden.
I have changed this so my editing area can be a bit cleaner.  The filename above the embedded file icon is too large for me.
Changed preference screen:
With filenames:
Without filenames:
Config file entry:
=> Optionally hide embedded file name in main note pane. 

debian/changelog
By using $upstreamversion-1 you are polluting Debian namespace.  Please use $upstreamversion-0$anythingyouwant for your own packages.  This makes it easier to update, track bugs, etc.
In all honesty, I usually advise upstreams against releasing their own binary distro packages.  It really isn't easy to get right and usually creates a bunch of problems. (Debian Maintainer speaking here)
=> Fix incorrect version

future/Makefile.am, future/po/POTFILES.in, future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_doc_rw.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h, future/tests/tests_misc_utils.cpp
- Added `CtActions` to keep action functions. Also, there is `CtAction`, so the naming might be a bit confusing.
- Added actions: `node_add` and `node_duplicate`. The property dialog, its controls, and adding a node into the treestore are working, but some functions are still stubs. And when the node gets focus, sig fault occurs. I suppose, the problem is with uninitialized rTextBuffer.
- Added ct_dialogs where I will try to keep dialogs from support.py.
- I tried another approach in naming string and containers helper functions, like std::trim, str::join, str::split, str::endswith, vec::remove and etc. I think, this way it is easier to remember what to type. What do you think? Also, I keep the previous duplicate functions just in case.
BTW, can `ct_doc_rw.h`, `ct_xml_rw.cc`, …
=> (Port to C++) node_add, node_duplicate

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_config.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h, future/src/ct/ct_sqlite3_rw.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h, future/src/ct/ct_xml_rw.cc, future/tests/tests_misc_utils.cpp
- Added node_edit and node_child_add.
- Made CtNodeData::foregroundRgb24 as Glib::ustring because char[8] doesn't copy by default and writing constructor and operator= for it is not worth.
- Removed duplicates for str:: in utils [(because of the comment)](https://github.com/giuspen/cherrytree/pull/455#issuecomment-457081452)
=> (Port to C++) node_edit, node_child_add

future/src/ct/ct_actions_tree.cc, future/src/ct/ct_app.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
- New nodes get a valid text buffer, this fixes crashes. Duplicated nodes have partly valid content, this is a temporary solution. So basically, adding node/subnode, duplicating become useful.
- Fixed node_edit - lost text buffer
- Fixed commented code in pref dialogs related to updating the textview params in real time
=> (Port to C++) fix text buffer

future/src/ct/ct_config.cc, future/src/ct/ct_config.h, future/src/ct/ct_pref_dlg.cc, modules/config.py, modules/support.py, sandbox/gtkmm/ct_config.cc
Allowes to switch off symbol replacement, like "* " and "(c)".
It can be quite annoying, and having such option would be nice.
Tested only python version, had trouble with building c-version.
=> New config option: "Enable Symbol Auto Replacement"

glade/styles.css
Fixes three issues in styles.css. 
The first bug is simple. Browsers get upset and issue a mixed-content warning when you import an insecure (http://) resource from a secure (https://) page. 
The second bug fixed is that every headings inserts newlines that do *not* exist in the original document. I sometimes use different headers on the same line in Cherrytree and, while the program itself renders them fine, the browser does not. Styling headings with     `display: inline;` fixes the issue.
The last and final bug that fixed is that whitespace does not render properly. If you have multiple levels of indentation in your notes and export to an HTML file, the indentation won't render. Applying the `white-space: pre-wrap;` style fixes the issue.
=> Styles revamp

future/Makefile.am, future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h, future/src/ct/ct_doc_rw.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h, future/src/ct/ct_xml_rw.cc
1. Add -lstdc++fs to work with std::filesystem
2. Add paste rich text/codebox/table/image/uri for the main viewer
3. More actions: text_row_selection_duplicate,  text_row_up, text_row_down
There is a small issue with tables. If copy & paste a table (through duplicate row, for example), then the pasted table takes several lines in the viewer, not one. But if click on the table and then click out of it, this fixes the table. Maybe it needs some redraw function after inserting, have you ever seen that bug?
As for my plans, I'm going to add signals and menus for anchored widgets, it should help with clipboard testing. And do you mind if I fix compiler warnings? It would be a separate pull request.
=> (Port to C++, edit menu) paste-clipboard, duplicate row, move row up and down

future/Makefile.am
ct_actions.h and ct_actions_format.cc both use std::optional and include the optional header. This is a c++17 way of implementing it. Before it has to be std::experimental::optional from experimental/optional. Since I believe this was intended for c++17 I would say tell gcc to actually use c++17
=> update makefile to use flag -std=c++17

future/src/ct/ct_menu.cc, modules/core.py, modules/menus.py
**Preview**: ![cherrytree-command-pallete](https://user-images.githubusercontent.com/13846618/71779868-bb504080-2fe0-11ea-856a-fdbb1c1ea64c.gif)
**Keybinding**: Ctrl+Shift+P
Currently all the menu items are shown in the command palette. User can search the palette by simply focusing and then typing in palette dialog window.
The search used is sub sequence search on lower cased strings.
**Note**: Ctrl+Shift+P was earlier used for PrintPageSetup but now its used for Command Pallete
=> Implement Command Palette Feature

snap/snapcraft.yaml
A few updates were needed
* change grade to stable so it can be in the snapstore
* add 7za to path
* remove unnecessary /usr/bin/7za to avoid confusion
* fix gtk2 themeing
=> Snap 7za not found

snap/snapcraft.yaml
The snapcraft.yaml was just pulling the version from whatever git said it was, which was 0.36.6 but when you run the cherrytree snap, the about says 0.38.11. So when a user installs cherrytree from the snapstore, they might notice the mismatch.
snapstore version before this commit: `0.36.6+git601.f8dc01c`
snapstore version after this commit: `0.38.11`
Hardcoding the version fixes this as well as making it look cleaner/more "official".
=> Hardcode version

future/src/ct/ct_const.cc, future/src/ct/ct_const.h
In [this commit](https://github.com/giuspen/cherrytree/commit/f8dc01ccc4713355148b7c793bea7639f435eca8), the `sv` language identifier was added (per localization [done here](https://github.com/giuspen/cherrytree/pull/610)), but the array size was not increased, which causes a build failure. This PR increases the size.
=> Ensure the CtConst::AVAILABLE_LANGS array is the correct size

cherrytree, modules/core.py, modules/main.py
Fix for #33, I suppose, for another languages it also will be work
- Code `win32_unicode_argv()` was found in Internet and quite popular, so I suppose it's safe to use
- It is not related to the issue, but I replaced in `file_startup_load()`
```python
open_with_file = open_with_file.decode(sys.getfilesystemencoding()).encode(cons.STR_UTF8, cons.STR_IGNORE)
```
with 'unicode()' because in `main.py` `arg_filepath_fix` already did the job for `open_with_file `.
=> Files with russian names won't open through command line under Windows #33

future/src/ct/ct_export2html.h, glade/script.js, glade/styles.css, modules/cons.py, modules/exports.py
*Does not reload page when clicking on Node
*Each node just contains its content, no tree data
*Tree data is stored just in index.html
*index.html uses IFrames to load just contents of the nodes
*Browsing feels very much like in Cherrytree
______________________________________________
**Before Fix**:
______________________________________________
______________________________________________
______________________________________________
**After Fix**:
=> Improve UX for Exported HTML

modules/core.py
**Ctrl+T** is mapped to **Insert Today's Node**
**Before Fix**: Going to today's node adds Year, Month and Day nodes to visited history.
**After Fix**: Just add Day node to visited nodes history.
=> Simplify node_date method and Fix visited nodes history

modules/printing.py, modules/support.py
resolved #60
resolved #119 
resolved #420
- pixbuf.scale_simple with INTERP_HYPER couldn't improve the situation, so scaling is done by cairo.
- a page-wide image could cross the page right border (because of curr_x > 0), now it is taken into account.
-  I tried to used cairo for scaling during an `insert/edit image` operation, but didn't see the difference between cairo and pixbuf.scale_simple, so left it as is.
=> export as pdf, the picture is blurry

modules/support.py
resolve #603
- on window, small width or height value really slows down `image.simple_scale` up to crush
- not a problem, but every value changing in one of  inputs calls `image_load_into_dialog()` twice because of updating value in another input.
=> [crush] - improper input validation on image properties form

glade/script.js, glade/styles.css, modules/exports.py
When exporting tree to HTML, by default all the nodes are collapsed,
and the collapsed nodes have a '+' button which can be clicked to expand the
node.
* Expand/Collapse nodes in HTML
* ExpandAll/CollapseAll buttons included
=> Add Collapse and Expand functionality in node tree of exported HTML

modules/core.py, modules/imports.py, modules/machines.py
Resolve #643
It's quite big changes in core but one of them fixes a serious issue. Sorry, for the long text.
There are two problems:
1.  **Really slow inserting of new nodes**. The problem is with finding a spare id, the algorithm `node_id_get` has O(n^2), when there are 20 nodes - it is fast, when 200 - it takes a second, when 800 - hmm.
So, firstly, I made it O(n) by finding max_node_id without checking every id.
Secondly, if it's import, first node uses (max_node_id + 1), second gets +1 without checking the whole tree (only checking `nodes_to_rm_set` just in case)
As a result 800 nodes are inserted in less a second. I think it will also make difference for other imports.
2. **Eating gigabits of memory by creating a lot of xml elements**. One of KeepNote documents is huge (5mb) and has …
=> Importing KeepNote to your cherry project take a long time

modules/support.py
Resolved #657 
The issue was that `on_treeview_event_after` was called only once in spite of pressing several keys. The better solution is just to take the selected row after closing the dialog.
=> fixes #657

future/Makefile.am, future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_file.cc, future/src/ct/ct_actions_find.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_config.cc, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_print.cc, future/src/ct/ct_sqlite3_rw.cc, future/src/ct/ct_state_machine.cc, future/src/ct/ct_state_machine.h, future/src/ct/ct_table.cc, future/src/ct/ct_table.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h, future/src/ct/ct_types.h, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h, future/src/ct/ct_xml_rw.cc
Changes compared to pygtk: 
- Buffers with simple text also use machine_state, I couldn't find API for build-in undo\redo for them. Don't think it's a big deal.
- Add more parameters in Codebox constructor, so no need for additional method calls to setup codebox
- Add code to clone and compare widgets
- Didn't implemented `objects_buffer_refresh`, looks like it is a big hack for some reason, maybe code will work without it?
=> (Port to C++) Undo\Redo

glade/script.js, glade/styles2.css, modules/exports.py
Based on #668 issue:
- Fixed not working 'Links Tree in Every Page' option
- Fixed css, made class names more sensible
- Fixed button size (tree +/-) under Firefox
- Replaced 100vh, 100vw by absolute position to removed overflow-x/y = hidden
- Removed not used `node_export_to_html2`
**Edit:**
- Fixed title: add `<br/>` after title, add css customization
=> Fixing html export

modules/findreplace.py, modules/lists.py, modules/support.py
Resolves #664 
**Tested**: on windows (didn't test on linux), fonts Sans/Segue UI (maybe not important), a random text with symbol U+1F5F9 (taken from [wiki](https://en.wikipedia.org/wiki/Check_mark))
**Issue**: `TreeIter.get_char` throws exception `RuntimeError: returned character can not be represented in 16-bit unicode` on a bad symbols.
**Fixing**: I added `try/except` to mitigate the problem in places that throw the exception while I worked with the prepared text.
Probably, the issue wouldn't repeat with Gtk3, because it has a newer codebase.
=> fixing "RuntimeError: returned character can not be represented in 16-bit unicode"

future/src/ct/ct_actions.h, future/src/ct/ct_actions_format.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h, future/tests/tests_misc_utils.cpp
- ported exec_code
- fixed `get_font_family`, `get_font_size_str`, they didn't work with two-word font families.
=> (Port to C++) exec_code

modules/core.py, modules/support.py
Partly fixes #427, #688 by replacing wrong 'apostrophe' and 'quotation mark' by the right ones. 
It only works for the main text buffer and codeboxes, text inputs and tables still are affected by the bug.
=> workaround for dead_diaeresis, dead_acute on win32

future/src/ct/ct_actions.h, future/src/ct/ct_actions_file.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_state_machine.h, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
P.S.: I removed `_setFontForSyntax` and related functions because there is no need for them, fonts are already put in style classes (like `.rich-text`, etc.). and textviews only need to change its class to change font.
=> (Port to C++) zoom_text, zoom_tree, node_go_back, node_go_forward

future/src/ct/ct_actions.h, future/src/ct/ct_actions_others.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h, future/src/ct/ct_codebox.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_pref_dlg.cc
- removed static ctMainWin from clipboard, there is no need for it
- changing colors for tree panel is working
- changing colors for textview will have two mode: light (classic) and dark (cobalt). Custom colors won't work.
CSS in terms of customizing gtksourceview is very limited and colors have to be set by theme manager (as I did now). The issue with custom colors is that bg and fg are not enough because other colors (selection, current-line, etc.) should be also changed. Gnote, for example, has a theme editor for customizing, to me, it looks easy to do, but can be postpone until first release.
It looks like, the only part to do are tables and then pre-release? 🎵 💃💃💃
=> (Port to C++) some fixes; theme for tree and textview

future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_state_machine.cc, future/src/ct/ct_state_machine.h, future/src/ct/ct_table.cc, future/src/ct/ct_table.h, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h, future/src/ct/ct_xml_rw.cc
- Fixed table appearance.
- Add 'Insert Table'
- Unified css class names.
- Redone the state machine. Turned out keeping copies of anchered widgets was not a good idea because they responded to events like mouse clicks. Now, states of widgets are kept in CtAnchoredWidgetState which doesn't interact with UI.
Going to work on table actions.
=> (Port to C++) start working on tables

future/src/ct/ct_clipboard.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_imports.cc, future/src/ct/ct_imports.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_table.cc
- rich text, tables, codebox are working, but for now images are not downloaded by url.
- changed the way to collect styles from html tags. Now, then a tag is closed, style is not dropped but reverted to the previous state.
- rich text nodes are squashed together if they have the same style.
- covert font sizes to small, H3, H2 sizes.
=> (Port to C++) paste html from clipboard

future/src/ct/ct_actions.h, future/src/ct/ct_actions_file.cc, future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_pref_dlg.cc
- moved from CtApp to CtMainWin: CtActions, CtMenu, CtPrint. CtMenu depends on CtActions, CtActions depends on current CtMainWin, so they cannot be global
- renamed `check_unsaved` to `try_to_save`
- simplified `reset`
- add systray
=> (Port to C++) sys tray

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
The fix is almost a hack, but I don't see the better solution currently. Or we need to give users ability to setup the scope of shortcuts (where they can be applied)
=> C++,  some keyboard shortcuts for node tree should not work in text buffer

future/src/ct/ct_storage_xml.cc, future/src/ct/ct_storage_xml.h
kind of to fix #774 
It's not a fix for the issue, but it mitigates the problem with opening a document.
When cherrytree loads a lot of widgets, they are trying to adjust their sizes (a few iteration per widgets), that causes freeze in cherrytree.
This PR delays reading text for every node until a node is selected. Still, it's easy to see the issue then you try to save a changed document because cherrytree needs to read text of all nodes before saving the document. (it sounds odd, but what we have currently)
I'll be working on fixing the issue with widgets.
=> C++, fix slow opening big xml files

future/README.md
Replaces #776 by:
1. Preserving the `cd` to comply with cmake's instructions
2. Add the `make` step to all Linuxes
=> Add the `make` step to build the binaries

future/src/ct/ct_actions_tree.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_const.h, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_table.cc, future/src/ct/ct_table.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_widgets.h
**Issue**: long first save (short freezing) on big xml files.
**Reason**: although node text buffer reading is delayed for xml and sqlite until node shows, we have to read all buffers for xml (not sqlite) to save a file. The reason for freezing is applying syntax highlighting for text buffers of nodes and text buffers of codebox with tables (>1000). 
Also, the issue can affect sqlite file during text search because we also have to read all buffers.
**PR**: delays applying syntax highlighting for all kinds of buffers until a node shows.
=> C++, delay applying syntax highlight until node shows

snap/snapcraft.yaml
Fixes #758 
Allows user to access files on removable media devices like flash drives. In order to use this though, the user will need to manually make the connection with the command:
```
$ sudo snap connect cherrytree:removable-media
```
This step is needed because the removable-media plug is not auto-connected but once this PR is accepted and built in LP (automatically), I'll petition for this plug to be auto-connected so the user doesn't need to do anything.
=> Add removable-media plug. Fixes #758

future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_file.cc, future/src/ct/ct_actions_find.cc, future/src/ct/ct_actions_format.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_export2pdf.cc, future/src/ct/ct_imports.cc, future/src/ct/ct_list.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_widgets.cc
comparing gunichar with char gives a lot of warnings, so I use  g_utf8_get_char to get gunichar from char string. It's ugly, but I don't think it will impact performance. Maybe later I will come up with better solution.
=> C++, fix warnings

future/src/ct/ct_export2pdf.cc, future/src/ct/ct_export2pdf.h
This fixes a bug I encountered on my future-text-formatting branch, where exporting to pdf fails because the key lookup for `curr_attributes` fails (since it is comparing pointers). Weirdly this does not seem to be an issue upstream, possibly something to do with the changes to tags in my branch?
I am not sure why this ends up not working since it _should_ be comparing identical pointers (both read from `CtConst::TAG_PROPERTIES`). Regardless, comparing strings is a more robust option here.
It also includes formatting changes to improve the readability (e.g `static_cast` instead of C style casts, `auto` when casting, etc) and one or two optimisations (e.g move instead of copy)
=> Fix searching map based on pointer key when exporting to pdf

future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_storage_sqlite.h
This fixes the schema mismatch error when importing CT SQLite files created before 49e7f9b for the C++ port
=> Added check for ts_* fields when populating and saving the treestore

future/src/ct/CMakeLists.txt, future/src/ct/ct_actions.h, future/src/ct/ct_actions_import.cc, future/src/ct/ct_import_handler.cc, future/src/ct/ct_import_zim_handler.cc, future/src/ct/ct_imports.h, future/src/ct/ct_md_handler.cc, future/src/ct/ct_md_parser.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_parser.cc, future/src/ct/ct_text_parser.cc, future/tests/data/md_testfile.md
This adds a basic markdown parser and an option to import from a markdown file/directory
The parser can currently handle:
- Lists (but only on one level)
- Headers (h1, h2, etc)
- Links 
- Italic text
- Bold text
- Strikethrough 
It can also apply multiple styles at once.
This does not include either pasting markdown or real-time formatting.
=> Add markdown parsing and importing

future/src/ct/ct_config.cc, future/src/ct/ct_config.h, future/src/ct/ct_import_zim_handler.cc, future/src/ct/ct_imports.h, future/src/ct/ct_md_parser.cc, future/src/ct/ct_parser.cc, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_text_parser.cc, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
This adds the ability to use markdown when formatting text. It is disabled by default and can be enabled by going to `preferences -> text -> Enable Markdown formatting (Experimental)`.
The formatting is checked when hitting space after a word or when pressing enter (enter checks the whole line, space checks the sentence), escaping characters is currently not supported but ctrl-z can be used to undo.
This also includes a rewrite of how the parser tokenizes the input and separates the tokenization from the parsing (which was necessary for parsing formatting). There are also general misc improvements to the parser and a fix for #869.
fixes #869
=> Implement markdown formatting of entered text

future/src/ct/ct_const.h
`gchar*` still causes issues, so I replaced it with `Glib::ustring` in some places as it was in the older ct_const.h.
`constexpr` doesn't work with `Glib::ustring`, but I like to have single `ct_const.h` without `ct_const.cc`, so changed `namespace` to `struct` to keep such behavior.
=> replace some gchar* with ustring in ct_const.h

modules/pgsc_spellcheck.py
Hi, I couldn't find the same file to edit in the future directory, so I hope making the change on master is ok.
The spellchecker flagged words with apostrophes as wrong, e.g. "didn't" would be highlighted. I Googled and found a patch that works, but it seems they never submitted it as a pull request so I'm going ahead and doing it here.
Implements https://gist.github.com/hcs64/993e77d4539f84ca33ca#file-spellcheck_apostrophe-patch
=> Fix apostrophe spell check

future/src/ct/ct_main_win.cc, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
Also, I tried to fix wrapping titles in TreeView, but it's broken and the bug in [bugzilla ](https://bugzilla.gnome.org/show_bug.cgi?id=653108) is not going to be fixed.
Gnome may introduce a new control in Gtk4 to fix the issue.
Closes #834
=> show/hide aux icon in TreeView

future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h
Resolves #892, copy\paste codebox in yaml format instead of plain text.
User can copy only one codebox (without additional text or by 'Copy codebox' comand) and paste only one too.
Example
```yaml
- codebox:
syntax: python3
width: 600
height: 200
width_in_pixels: true
highlight_brackets: false
source: |-
def compound_interest(principle, rate, time): 
CI = principle * (pow((1 + rate / 100), time)) 
print("Compound interest is", CI) 
compound_interest(10000, 10.25, 5)
```
Don't change block indent (6 spaces)
User can add additional fields between `codebox` and `source`, e.g. 
```yaml
- codebox:
title: some example
``` 
For now, I use a custom yaml parser. If it caused issues, it would be replaced by a normal library.
=> copy\paste codebox in yaml format

future/debian/control
This lets us build the package on arm64, armhf, armel and i386 instead
of just amd64.
=> Set architecture to any

future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_splittable.h
This implements Table of Contents inserting for the C++ port.
I think this matches the behaviour of the python version 100%, it uses the same anchor structure for nodes (`h<level>-<num>`) and the same character set for the list bullets.
There is a bug which I noticed which causes a segfault if an anchor is removed and then another node is selected. This is a general issue with anchors in the C++ version I think since I get the same bug if I use "insert anchor".
=> Implement Table of Contents inserting for C++

future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_table.cc, future/src/ct/ct_table.h
Supports excel style csv with comma field delims and double quotes for strings.
The reason it for the ugly code in `from_csv` where it reads the data in chunks is because it needs to be able to handle newlines in cells
=> Add CSV handling to CtTable in the C++ port

future/src/ct/ct_parser_md.cc, future/src/ct/ct_parser_text.cc
This fixes a crash which occurred due to finding a close tag without an open tag. It also makes the parser more resilient to errors so that even if parsing a line (at worst) fails it should keep going
=> Fix crash in the markdown parser 

future/src/ct/ct_imports.cc, future/src/ct/ct_imports.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_parser.cc, future/src/ct/ct_parser.h, future/src/ct/ct_parser_md.cc, future/src/ct/ct_parser_text.cc, future/tests/tests_misc_utils.cpp
This is a much improved version of the markdown parser. 
It adds
- Codeboxes
- Tables
- Headers using `==` and `----`
- Images 
- Monospace
- Horizontal spacers
- Bold and italic at the same time
And fixes several issues with conflicting symbols.
This also includes functions for image, codebox, and table xml serialising under the `CtXML` namespace. I have not changed the existing functions in `CtHtml2Xml` or the respective widgets but they can now be changed to use the needed function instead of duplication.
Note that widgets (such as codeboxes, tables, and images) are still inserted into the active node when import is selected. Which I am guessing has something to do with `from_xml_to_buffer`.
=> Feature improved markdown

future/src/ct/ct_config.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h
This adds Pandoc usage to the HTML parser. If the syntax format is supported (currently `markdown` and `latex`) then it will be run through pandoc (with a warning if pandoc could not be found). This works for codeboxes and nodes with syntax highlighting.
I have also added a switch in `CtConfig` as `usePandoc` which currently is always true but can be used to disable pandoc exporting in the future (i.e if the user wants unformatted text for some reason)
Ref #878
=> Use Pandoc when exporting to HTML

future/data/script3.js, future/data/styles3.css, future/src/ct/ct_export2html.cc
This improves the styling of the output HTML, mostly it only uses `style3.css` but there is also some html injection using `script3.js`.
Changes:
- Tree panel can be shown/hidden using a button between it and the `page_frame` iframe, mousing over the button when closed will open it
- Background is now `#EEEEEE` for everything
- Backgrounds for widgets (i.e tables) is now `rgb(197, 197, 197)` (`#FFC1C1C1`)
- Links on the tree expand to the full width of the row and the row lights up (`rgba(197, 197, 197, 0.7)`) on mouse over instead of the link being underlined
- The `+/-` buttons on the tree no longer have borders and are vertically centred in the row
- The `index` text at the top of the tree panel has been moved up and made `h1`
- Buttons no longer have borders or backgrounds and instead …
=> Improve HTML output

future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_help.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h
This implements custom link actions for the C++ port.
It invokes the external application using `std::system`, GSubprocess is a bit heavy for this I think but it does have the issue that output of the child muddies the output of cherrytree 
It also adds a `path` class to `CtFileSystem` which is basically a version of `std::filesystem::path` with only the bits that are currently needed. I added this because I needed a way to format paths correctly across platforms and didn't want to write `get_proper_platform_path` every time, but it also has `operator/` overloaded for `g_build_filename`.
=> Implement custom link actions

future/src/ct/ct_clipboard.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_storage_control.cc, future/src/ct/ct_storage_control.h, future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_storage_sqlite.h, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_storage_xml.h, future/src/ct/ct_table.cc, future/src/ct/ct_table.h, future/src/ct/ct_widgets.h, future/tests/tests_misc_utils.cpp
Resolves #854
**Issue**: saving pixbuffers into buffers is slow. Many images (e.g. when nodes are imported, or edited node has a lot of images) noticeably slow down saving.
**Solution**: gather all pixbuffers and save them into buffers concurrently. Pass saved buffers in `CtStorageCache` (which can be skipped, then code will work as it worked before)
Notes:
- `tbb::parallel_for` is ideal here, but that adds `libtbb-dev` dependency. Concurrent STL also uses `tbb`, and for some reason it doesn't parallel calculation, I don't know why. Glib has some task classes, but they are really complicated and I concur they have different purpose.
I wrote `parallel_for` by using `std::thread` and `std::packaged_task`. The function is covered by unit tests.
- on my machine, 50 images: old code - 16 …
=> concurrently convert images into string before node saving

future/src/ct/ct_config.h
Resolves  #930
But config.cfg will old file paths will still show double backslashes, to users have to themselves to remove them one way or another.
=> fixes reading double backslashes from config file

modules/cons.py, modules/core.py, modules/support.py
Resolves #889
Fixes situation when you press Control button, we get Control signal; when you release this Control button, we get ISO_Prev_Group instead of Control (LMDE 4, Debian 10)
It only affects pygtk, C++ version uses different approach.
=> fixes gtk not sending paired released Ctrl for pressed Ctrl (broken zoom)

future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_storage_sqlite.h
The SQLite storage manager will now check corruption on 
- `test_connection()`
- `populate_treestore()`
- `import_nodes()`
It prints a warning to the terminal with the issues reported by SQLite and displays a warning to the user. I think handling it all in `_check_database_integrity()` and not throwing is ok?
=> Add integrity check to SQLite storage

future/src/ct/ct_clipboard.cc, future/src/ct/ct_filesystem.h, future/src/ct/ct_menu.cc
Resolves #28
Though old code seems to work, for some reason, png in clipboard is not recognizable by apps.
To fix it, only on Win32, I directly put pixbuf into clipboard without other formats. Copy such png back to CT seems to be working.
=> fixes copy images from CT to MS Paint

future/src/ct/ct_codebox.cc, future/src/ct/ct_filesystem.h, future/src/ct/ct_image.cc, future/src/ct/ct_logging.h, future/src/ct/ct_misc_utils.h, future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_table.cc, future/tests/CMakeLists.txt, future/tests/test_consts.h, future/tests/tests_encoding.cpp
- fixes `fmt::format` crash with Glib::ustring because `std::ostream` couldn't work with win32 locale
- adds test for `fmt::format` 
- fixes crash during saving in sqlite due to `Glib::locale_from_utf8`
=> fixes encoding issues on win32

future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h
- Resolves  #948
- Shows toolbar changes in real time without the app restart
=> fixes saving toolbar changes in PrefDlg

future/src/ct/ct_parser_md.cc, future/src/ct/ct_parser_text.cc, future/src/ct/ct_widgets.cc
This fixes an issue raised [here](https://github.com/giuspen/cherrytree/issues/444#issuecomment-647577303). Basically the parser was overzealous with erroring out.
To note, the formatter is still not perfect (case in point: tables are problematic since it is done line by line, but since that's more advanced I don't think it should be expected to work). This also removes formatting on space, replacing it with only on enter since one space is pretty restrictive. Perhaps there should be a config option for when to do formatting?
Also this adds `_` as italics (forgot that part of the syntax, oops)
=> Fix issues with md formatting

future/src/ct/ct_clipboard.cc, future/src/ct/ct_imports.cc, future/src/ct/ct_main_win.cc
- paste didn't work on win32 because of the wrong target "text/html", should "HTML Format"
- paste an image caused crash, the issue is in a wrong tooltip for the image.
Fixes #958
=> fixes paste on win32

modules/main.py
It's not available on macOS, and so generates a warning every launch.
I'm not a python guy, but this looked right and seems to stop the warning on my systems.
=> main.py : don't try libc.prctl on MacOS

future/src/ct/ct_main_win.cc, future/src/ct/ct_treestore.cc
Fixes two issues:
- Using `get_embedded_pixbufs_tables_codeboxes` before filling up `textbuffer`. It happens for 'save as' into sqlite files. For xml files,  `textbuffer` is called before  `get_embedded_pixbufs_tables_codeboxes`, so there was no issue there.
- The storage replacement after 'save as' was not proper. It was easy to see, when after 'save-as' into sqlite file and selecting a node with widgets, widgets show in spite of sqlite file was missing them. To fix this, I reopen new file.
=> fixes `save as`

future/src/ct/ct_export2pdf.cc, future/src/ct/ct_export2pdf.h, future/src/ct/ct_misc_utils.h
This is the first part to implementing: #942 
I ended up going for the redesign in the end because the custom formatting worked up to a point but was incredibly hacky and trying to get it to align properly and format correctly was a nightmare. 
The new design works as follows:
- `CtPrintData` has a list of `CtPrintable`'s which are everything which can be drawn to the pdf  (i.e text and widgets). 
- Page count is calculated based on the sum heights of all the `CtPrintable`'s in the print data divided by the size of each page (rounded up, +1 if there is any remainder)
- `CtPrintable` exposes `height()`, `width()`, `setup()`, `print()` and `done()`. `setup()` needs to be called before the printable can be used and `print()` displays the printable in the given context and returns the final …
=> Redesign pdf exporting code

future/src/ct/ct_export2pdf.cc, future/src/ct/ct_export2pdf.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/tests/tests_misc_utils.cpp
This is the second part to #942
Image anchors are now processed, anchors are inserted as the unicode anchor emoji (⚓) instead of the image because it was simpler, since it takes a `CtImageAnchor` in the relevant ctor however, this is easy to change. 
This adds two new classes, `CtDestPrintable` and `CtLinkPrintable` where `CtDestPrintable` is what processes `CtImageAnchor`'s, and `CtLinkPrintable` just applies the cairo link tag and makes its text blue.
Internal destinations are represented in the form `n.<node id>.[section (e.g h1-1)]`, the section part is optional. External destinations are processed by `CtStrUtil::external_uri_from_internal()` which converts an internal uri (e.g `webs https://example.com`) to an external one (and decodes file paths).
=> Implement links in exported PDFs

future/src/ct/ct_app.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_pref_dlg.cc
- `is_embedded` doesn't work because it should be called in main event loop
- fixed an issue when New Instance could create a hidden window
- changed "Quit" label into "Hide" when it works as hide
Didn't check it on Ubuntu, but I think it should work
=> fixes behaviour systray icon

future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, modules/core.py
Resolves #987
Issues:
- From #987: double click in any empty place (or an expand icon) of the tree panel causes expanding/collapsing of the selected row. So, double click on an expand icon of some row, doesn't expand that row, but expand the selected row. To fix it, I check if selected row is under cursor.
- double click sometimes doesn't work and this looks like click skipping. To fix it, I use `row activated` signal, in this case, double click works smoothly.
-  `row activated` signal doesn't work right when the `one click` option is on. In this case, I use old double-click, although it can have the mentioned issue.
Fixes are both for pygtk and gtkmm3
=> fixes collapsing/expanding nodes on double-click

future/src/ct/ct_pref_dlg.cc
Looks like `Glib::signal_idle()` gives not enough time for `is_embedded`, thus I added a timeout 300 msec. Also, I disabled the dialog for that period, so user cannot fast click that option several times.
=> fixes systray again

future/src/ct/ct_actions_import.cc, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_storage_sqlite.cc, future/src/ct/ct_storage_sqlite.h, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_storage_xml.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
Resolves #979
- Node order wasn't right after using commands "Node Up" and "Node Down", though moving nodes by drag-drop was OK. The reason is that node sequence swapping didn't work because node sequence was never loaded. It was usually OK because we recreated node sequences every time and it only caused extensive db writing. Fixed it by loading node sequences. 
- Users complained on some options in PrefDlg that should not work, so I disabled them.
- Switching off "Create a Backup Copy Before Saving" didn't work. Fixed it
=> Fixes node sequences after moving nodes.

modules/config.py
Typo lead to code exec issues for both
=> Fix powershell/perl typo in modules/config.py

future/src/ct/ct_actions_import.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_imports.h
Resolves #1000 (such a nice issue number)
Adds support for native dialogs, to use it, start the app with `GTK_USE_PORTAL=1` on kde systems. On win32 there is no need for any flags. Small drawback is mime filtering is not supported there, there is only pattern filtering.
=> uses Gtk::FileChooserNative

.travis.yml, future/src/ct/ct_app.cc
The second start of cherrytree brings up the main window of the first instance (quite intuitive behavior for users ). Also, if all windows are hidden in a system tray, it makes them all visible.
=> Fixes hidden app in a missing systray

future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_help.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_filesystem.cc, future/src/ct/ct_filesystem.h
Fixes #1004. 
- use `xdg-open` to open files/directories/links on linux (fiy, inkscape do the same). 
- renames related functions.
=> fixes CT cannot open links on KDE

future/src/ct/ct_actions.h, future/src/ct/ct_actions_find.cc
Resolves #1006
- fixes crash and shows an appropriate dialog when regex pattern is invalid
- allows using regex in replacement text (it's not about searched text/pattern), before that replacement text just replaced the matched text. The solution is not ideal, but I don't see how make it better
- small refactoring to speed up thing: regex is created only once instead of per iteration
=> fixes regex in search/replace

future/src/ct/ct_actions.h, future/src/ct/ct_actions_view.cc, future/src/ct/ct_const.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_pref_dlg.cc, modules/config.py, modules/menus.py
Resolves #1010
- adds a special element "Split Toolbar" in Preference dlg to split and thus to create more toolbars than one. Maybe we need a new icon for it.
- fixes pygtk which doesn't work well with a new toolbar element
- renames functions from `toolbar` to `toolbars`
=> addes abitlity to create several toolbars

future/src/ct/ct_export2pdf.cc, future/src/ct/ct_export2pdf.h, future/src/ct/ct_table.h
This fixes several issues introduced with the refractor of pdf exporting. 
- Codeboxes and tables will now extend over several pages.
- Page breaks are now properly calculated as part of required page number.
- Wrapping is now accounted for when calculating the number of pages.
I have tested this with ~200, ~2000, and ~4000 page documents. Note that page breaks are appended on the end of each page, which causes an extra page on the end of any document using page breaks. I do not see this as much of an issue but it would be a trivial fix if needed.
Fixes: #1012
=> Fix pdf exporting issues after refractor

.travis.yml
This adds a bionic build to travis. 
In order to get it to build on bionic I had to install gcc9 from the "testing" toolchain repo. I have also removed the cmake build from source since it is no longer needed.
~~Build times are _much_ faster now, testing this it took 8-9 minutes to build the linux ones vs the 20+ minutes it used to take~~ nvm I am wrong, this does not seem to affect build times
=> Add travis bionic build

future/src/ct/ct_export2pdf.cc, future/src/ct/ct_export2pdf.h
I thought I would never finish that work, but here we are.
I couldn't much understand how to fix the previous code, so I rewrote it back using the same pygtk version, but actually improved (and it still supports links).
- `CtExport2Pango` just returns tokens (text, link, dest, new page, widget) from buffer
- `CtExport2Pdf` makes only one pass to create pages based on tokens and uses these pages to draw pdf.
The main difference is that there is only one pass instead of two (before it was to calculate element positions to figure out number of pages and then do it again to draw elements).
The second difference, a page has lines (one line per `y` coordinate), every line has a number of elements (line of text, widgets). So it is much easier to see what is going on. 
The third difference, …
=> Redesign pdf export

future/src/ct/ct_actions_edit.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_table.cc
Partly resolves  #1037
- remove "Click Me" in table header
- popup menu is the same for header or ordinary cell, so adding new columns is possible from any cell
=> join popup menus for header and ordinary cells

future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_import.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_app.h, future/src/ct/ct_config.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_filesystem.cc, future/src/ct/ct_filesystem.h, future/src/ct/ct_image.h, future/src/ct/ct_main_win.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_parser.h, future/src/ct/ct_parser_text.cc, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_table.cc, future/src/ct/ct_table.h, future/src/ct/ct_widgets.h, future/tests/tests_filesystem.cpp, future/tests/tests_misc_utils.cpp
Resolves #1029 , issues are caused by functions which don't understand UTF8 file names on WIN.
1. Cannot open links in the note if the address uses Russian characters. Caused by file streams, removed them everywhere except imports. String streams don't have that issue.
2. Files attached to a note with names in Russian cannot be opened. ShellExecute doesn't understand UTF8, fixed it by converting paths to UTF16,
3. Removing some characters from a node name. It was caused by `str::trim` which worked with ANSII symbols instead of UTF8. `str::xml_escape` also worked with ANSI, I'm surprised it hasn't cause any issue so far.
=> Fixes reading/writing files on WIN

future/src/ct/ct_config.h, future/src/ct/ct_export2pdf.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_widgets.cc
Resolves #1055, some fonts cannot display checkbox symbols and symbols from languages. For some reason, Linux is not affected by this issue, I suppose, font config already has a fallback font.
- add fallback font "Sans" for textview, codebox, treevew. Also, fixes pdf output.
- change a cursor for checkboxes.
=> add fallback font support

future/src/ct/ct_widgets.cc
Resolves #1068
For some reason, `get_iter_at_location` works not precisely while `get_iter_at_position` works great.
I didn't remove `get_iter_at_location` in other places because precision doesn't matter there.
=> fixes checkbox click-zone being misaligned

future/src/ct/ct_config.cc, future/src/ct/ct_config.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_storage_control.cc, future/src/ct/ct_storage_control.h
Resolves #1061
- custom backup dir
- if there is any issue with custom backup dir then standard backup is used
- removed save backup only once, now it's done every save
- the issue with long names in Win32 exists, but I did nothing to avoid it.
=> Custom backup dir

future/src/ct/ct_clipboard.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_image.cc, future/src/ct/ct_image.h
=> adds File Attachment Type-Based Icons on Linux, thanks to @metal450

src/ct/ct_actions.h, src/ct/ct_actions_format.cc, src/ct/ct_actions_others.cc, src/ct/ct_dialogs.h, src/ct/ct_export2html.cc, src/ct/ct_export2pdf.cc, src/ct/ct_export2pdf.h, src/ct/ct_main_win.cc, src/ct/ct_misc_utils.cc, src/ct/ct_misc_utils.h, src/ct/ct_types.h, tests/tests_misc_utils.cpp
- CtMiscUtil::get_link_entry is used to get link data
- removes exceptions for `invalid` links during pdf export
- adds underlining for links in pdf export ( #1113)
=> unified link data parsing by CtMiscUtil::get_link_entry

src/ct/ct_actions_find.cc, src/ct/ct_dialogs.cc, src/ct/ct_dialogs.h
Possible fixes freezing (#1105, #1078)
Fixes missed results, caused by wrong condition.
Freezing is caused by gtk bug. Maybe there are other freezing situations, but I found only one:
Two nodes. First node with codebox (content = 123) at the very beginning (otherwise bug doesn't 'work'). The second node other text. Select the second node and the text there. Search all nodes with 123, it is freezing when it tries to select codebox.
The temporary solution is to unselect text in the current buffer.
=> Fixes search

src/ct/ct_actions.h, src/ct/ct_actions_edit.cc, src/ct/ct_actions_export.cc, src/ct/ct_dialogs.cc, src/ct/ct_dialogs.h, src/ct/ct_export2html.cc, src/ct/ct_export2html.h, src/ct/ct_menu.cc, src/ct/ct_types.h
@giuspen , I couldn't come up with a nice menu title for the command, so I decided just to add an option 'Single File' on the export dialog. If you have any comments about that, I'd be glad to hear them. 
To be honest, I'd prefer that commands have similar behavior; it's better to have either two commands for HTML export (multi/single) or join plain text export commands into one command.
=> option to export HTML as a single file

src/ct/ct_treestore.cc
Resolves the second case in  #1189
=> `get_node_name_from_node_id` should work with invalid node id

src/ct/ct_app.cc, src/ct/ct_codebox.cc, src/ct/ct_main_win.cc, src/ct/ct_menu.cc, src/ct/ct_menu.h, src/ct/ct_table.cc
Resolves #1289
@giuspen , the fix is quite simple, it shifts images by setting margin in css. But for some reason from time to time, gtk stops drawing images in Menu until you hover mouse over menu item causing redrawing (it happened several times on Linux and Win).  
Maybe we will have to disable this fix if people complain
=> fixes image placement in MenuBar/context menu

src/ct/ct_actions.h, src/ct/ct_actions_others.cc, src/ct/ct_const.h, src/ct/ct_image.h, src/ct/ct_menu.cc
Resolves #1301
@giuspen , FIY, it adds new translate strings and uses standard 'ct_edit' icon for popup menu item.
=> new command to rename emb. files

src/ct/ct_app.cc, src/ct/ct_app.h
Resolves #1339
Also, I put all UI initialization from App constructor into a separate function, so second instance can start really fast. Actions actually are really convenient way to send different commands from command line into the existed instance (e.g. inkscape uses them that way)
=> adds `--new-window` option

src/ct/ct_actions.h, src/ct/ct_actions_export.cc, src/ct/ct_app.cc, src/ct/ct_app.h
--export_single_file can be used to export to a single text or html
file from the command line.
Also prevent "No Node is Selected" popup from appearing during export.
=> New --export_single_file export option

snap/snapcraft.yaml
Since setup.py moved to the pygtk2 dir, the snap build had to be fixed. This build also is based off of the 0.99.24 tag.
=> Snap updates to fix build and release 0.99.24

snap/snapcraft.yaml
It turns out that the snapcraft used on launchpad (which publishes to the snap store) was expanding this variable while my locally built snaps didn't have the problem.
This will fix the 0.99.24 snap runtime.
Once this change is merged, it will build and be available in the store and then to test:
```
$ sudo snap install cherrytree --edge
```
=> Fix the cherrytree shebang

scripts/metainfo_xml_write.py
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This PR was done while working on reproducible builds for openSUSE.
=> Allow to override build date with SOURCE_DATE_EPOCH

src/ct/ct_table.h
Add one more missing `#include <optional>` to make GCC 11 happy.
This is an additional (and final, it appears) fix for #1436.
=> More GCC11 fixes

README.md
Added build description for Gentoo.  Used repo supplied ./build.sh instead of cmake commands.  ./build.sh handles the need to use mkdir
=> Update README.md - Added build description

README.md
Add gnome-icon-theme dependency to Ubuntu build instructions.
`cherrytree` launch aborts with `gtk-icon-theme-error-quark` exception when gnome-icon-theme isn't installed in a chroot environment.
=> Add gnome-icon-theme dependency

language-specs/nasm.lang, src/7za/CPP/myWindows/wine_date_and_time.cpp, styles/Amy.xml
This is flagged by package review tools in Fedora and Debian.
See, e.g, https://lintian.debian.org/tags/old-fsf-address-in-copyright-file.html
Signed-off-by: Ben Cotton <bcotton@fedoraproject.org>
=> Correct the FSF's postal address

src/ct/ct_app.cc, src/ct/ct_main_win.cc
Pull request to address Cherrytree Issue #1703 & #1704.
=> bugfix - status icon (missing / bad render) #1703 and tree node visibility #1704

src/ct/ct_actions_others.cc
pass a std::string to fmt instead of a Glib::ustring
Fixes #1739
=> fix build with fmt 8.0.0

data/cherrytree.desktop
This adds the line explained on [Linmob.net](https://linmob.net/phosh-0-12-app-drawer/)
It could also be the kde variant.
Also I'm hesitant about the value. If its both Workstation and Mobile, there is no differentiation.
However maybe later this can become handy together with #1024.
=> Added FormFactor Property to .desktop

snap/snapcraft.yaml
* Add gnome extension to reduce size
* Remove unnecessary plugs
* Minimized build and stage packages
* Alphabetized build and stage packages
* Make sure to use the libpangoft in the archive, not the gnome extension
* Remove unnecessary hooks
=> Additonal changes for core22

src/ct/ct_filesystem.cc
this function crashes if the filename is an empty string just return an empty string if it comes in as one
see: https://github.com/giuspen/cherrytree/issues/2112
=> legacy_canonicalize_filename: manage empty filename

CMakeLists.txt, src/7za/C/Alloc.c, src/7za/C/Alloc.h, src/7za/CPP/7zip/Archive/Cab/CabBlockInStream.cpp, src/7za/CPP/7zip/Archive/Cab/CabHandler.cpp, src/7za/CPP/7zip/Archive/XzHandler.cpp, src/7za/CPP/7zip/Common/StreamObjects.cpp, src/7za/CPP/7zip/Compress/DeflateEncoder.cpp, src/7za/CPP/7zip/Compress/LzmaDecoder.cpp, src/7za/CPP/7zip/Compress/ZDecoder.cpp
Fixes two issues I've found when trying to compile using MSYS2 clang64
```
C:/msys64/clang64/include/libxml++-2.6/libxml++/validators/xsdvalidator.h:149:8: error: no template named 'auto_ptr' in namespace 'std'
std::auto_ptr<Impl> pimpl_;
~~~~~^
6 errors generated.
```
and
```
ld.lld: error: duplicate symbol: MyFree
>>> defined at C:/msys64/home/user/cherrytree/src/7za/C/Alloc.c:82
>>>            lib7za_static.a(Alloc.c.obj)
>>> defined at SETUPAPI.dll
```
=> Fix compilation for MSYS2 Clang64

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Docker build environment provided by VSCode devContainers is currently broken due to missing ubuntu dependencies declared in the Dockerfile.
Also changed to "ms-vscode.cpptools-extension-pack" to be available as an extension in the docker build environment.
=> Added missing dependences to Dockerfile for dev container

src/ct/ct_config.cc
Build is failing with fmt 10 due to changes with how enums are treated.
Specifically, an enum now need to have a `format_as` function, or be casted to its underlying type:
```
Removed deprecated implicit conversions for enums and conversions to primitive types for compatibility with std::format and to prevent potential ODR violations. Use format_as instead.
```
=> Fix building with fmt 10.

build.sh
build.sh does not properly discover and tag DISTRIB_RELEASE on Debian testing and Debian unstable/sid releases, resulting in the following error message when running 
> ./build.sh deb
`mv: cannot move 'cherrytree-1.0.3-Linux.deb' to 'cherrytree-1.0.3~Debiantrixie/sid_amd64.deb': No such file or directory`
This is due to `/etc/debian_version` on Debian's testing & unstable branches not using an explicit version number, but instead using the release _codename_/sid
> drasey@stewie:~/git/cherrytree$ cat /etc/debian_version 
> trixie/sid
This PR is aims to resolve that by checking if /etc/debian_version includes **_sid_**, and using the release codename (trixie in my case) for DISTRIB_RELEASE.
=> Update build.sh to properly discover and tag DISTRIB_RELEASE on Debian testing and Debian unstable/sid releases.

BUILDING.md
Add debian package 'file' to build dependencies to resolve "CPack: Create package" error.
**Resolves** #2411
=> Add debian package 'file' to build dependencies to resolve "CPack: Create package" error.

styles/gruvbox-dark.xml, styles/gruvbox-light.xml
Add gruvbox style them from GtkSourceView
The XML style schemes were not made by me, and are protected under GNU Lesser General Public License v2.1. I just imported them to cherrytree.
Examples of how it looks, on my machine. I have built from source and have had 0 issues so far.
=> Add Gruvbox light and dark theme

po/pt.po
Now has both "Open File" and "Open Folder"
Fixes giuspen/cherrytree#2516
=> Fix duplicate "Open File" in PT translation

src/ct/CMakeLists.txt, src/ct/ct_actions.h, src/ct/ct_actions_file.cc, src/ct/ct_dialogs.h, src/ct/ct_dialogs_sel_node.cc, src/ct/ct_menu_actions.cc, src/ct/ct_menu_ui.cc
This adds a new quick-select dialog much akin to the Command Palette, except instead of selecting commands, it fuzzy finds on node name/path.
This somewhat improves the UX, in my opinion, for quickly switching nodes. There is the `Ctrl+T` shortcut for "Find in Multiple Nodes...", but that search box does not have suggestions or live filtering.
The inspiration for this feature comes from the `Ctrl+P` default binding in VS Code where you can search for a file very quickly and switch to it. I have put a default binding of `Ctrl+Alt+P` in, but that is a very rough "what I could find that wasn't already used" kind of map and I am very open to changing it.
Also note, if there is some reason this feature hasn't been in CherryTree I am happy to abandon the PR. I just think it might make a really …
=> (feat): Adding new quick-select dialog

src/ct/ct_export2html.cc, src/ct/ct_storage_control.cc, src/ct/ct_storage_multifile.cc, src/ct/ct_storage_sqlite.cc
CherryTree fails to build on Fedora Rawhide due to errors introduced by fmt 11. This commit fixes all of the remaining errors raised during compile.
Fixes #2548
This builds successfully on both Fedora Linux 39 and Fedora Rawhide. The resulting binary passes a basic functionality test.
=> Fix formatting issues with fmt 11 (#2548)

src/ct/ct_codebox.cc
The `update_toolbar_buttons` function, which is called whenever a codebox is reconfigured or when codebox toolbars are en-/disabled, works by removing all the toolbar buttons and readding them as necessary.  It was using the `_toolbar.append()` function which sets up the buttons' callback at the same time.  Because the ToolbarButton objects are persistent, an extra copy of the callback was being connected each time the button was removed and readded, so Gtk thought we wanted to run it multiple times.
Now, the buttons' callbacks are setup once using
`signal_clicked().connect()` in the codebox constructor and the `update_toolbar_buttons` function uses `_toolbar.insert()` which doesn't affect the callbacks at all.
Fixes #2628
=> Fix duplication of codebox toolbar callbacks

.devcontainer/Dockerfile
I recently went through the current Gentoo [ebuild for cherrytree](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-text/cherrytree/cherrytree-1.2.0.ebuild) while troubleshooting something, and noticed that the tests are currently restricted from running by default, with the comment:
> Has deps that aren't available in ::gentoo repo
However, I'm able to build the tests on my Gentoo machine with no problem, despite not having `cpputest` installed or having taken any other special action. The only mention of `cpputest` I could find was in the devcontainer Dockerfile. I don't see any other  documentation specifying test dependencies either.
Please let me know if this change is in fact invalid, and/or if there are other testing dependencies that I'm unaware of, (apart from having an X …
=> update test dependencies

src/ct/ct_app.cc, src/ct/ct_app.h, tests/tests_exports.cpp
Running the tests using ctest with multiple jobs does not succeed, due to the Gtk application re-using existing instances which leads to inconsistent behavior. This change allows the test application instance to specify that non-unique behavior is required.
This can be triggered by executing `ctest -j 2 --tests-regex "Export"`. The tests will fail with any number of jobs greater than 1, unless the jobs are in fact executed sequentially (for example if system load is too high).
This is an issue for the test stage in the Gentoo ebuild, which by default will use the number of jobs that is configured for the build system. If this is greater than 1, then the tests will likely fail. One [possible fix](https://github.com/gentoo/gentoo/pull/40462) for this is to override the number of jobs to …
=> fix multiprocess export tests
