giuspen/cherrytree

locale/zh_CN.po
update zh_CN.mo for some wrong spelling.
=> update zh_CN.mo for some wrong spelling.

modules/imports.py
This should add the note type file when importing from a BasKet folder. Since it's my first time working with cherrytree I'm not sure if I missed something. Code should be tested thoroughly.
=> Possible fix for #72

locale/es.po
Small corrections misspellings in spanish translation
=> Correct typos [es]

locale/es.po
Upsss, sorry I added another typo.
=> Correct typo [es]

language-specs/yaml.lang
Hi Giuseppe!
It might be useful to add Yaml syntax highlighting for everyone since it's quite common these days.
I'm already using it personally. Any objections?
Kind regards,
Sergei
=> Add Yaml syntax highlighting

modules/core.py
Fixes incorrect set_tooltip_text call
=> Fix syntax error

modules/cons.py
Sometime there is a need to change the temp folder location.
=> Optional ability to change temp folder for other OS

modules/config.py, modules/core.py
Added  misc.journal_day_format option (default: "%d %a") to config.cfg  to be able to change the node format
=> Add config option to customize 'Insert today's note' node

future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h
Added a toolbar. 
To test: click on the first button "Add node" writes "CtApp::add_node() is called" in the application output.
=> (Port to C++) add a toolbar

future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h
Added functions to generate different popup menus. 
Added showing node popup menu for the right button click on the tree node as an example. Although there is an issue, sometimes there is no event for button clicks on nodes, I have no idea why is so, tried signal_button_release_event and signal_button_press_event (behaves even worse).
=> (Port to C++) popup menus

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
- Added `node_toggle_read_only` action.
- Added CtTreeIter class to conveniently get/set the node data.
- Added 'node name header', buttons currently don't work because code relies on the state machine which is missing
=> add node_toggle_read_only

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
- Added mentioned in the title actions.
- The hotkeys for these actions works ok, but there are still some issues that I try to fix later. 
- I implemented `widget_set_colors`, but it doesn't work as should. If you have time, can you look at it?
=> (Port to C++) node_date, node up/down/left/right

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_doc_rw.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
- Showing bookmark icons
- Adding/Removing bookmarks
- Building bookmarks menu
- Bookmarks dialog
=> (Port to C++) bookmarks

future/Makefile.am, future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_format.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h, future/src/ct/ct_codebox.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_export2txt.cc, future/src/ct/ct_export2txt.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_imports.cc, future/src/ct/ct_imports.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_table.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_xml_rw.cc
Cut and copy to clipboard (text, plain text, row) should more or less work for the main text view. As for codebox, it will be done when I can get the current codebox.
Also, paste from clipboard is done for plain text, I'm going to work on other formats.
=> (Port to C++, edit menu) cut-, copy-clipboard

future/Makefile.am, future/po/POTFILES.in, future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_codebox.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_export2txt.cc, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_menu.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_table.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
- Simplified getting popup menu
- Finished popup menu actions for anchor image / emb file
- Had to put `CtAnchoredWidget` and `CtTreeView` in the separated file `ct_widgets`, otherwise I couldn't compile the project ("invalid use of incomplete type") when started using CtAnchoredWidgets in `ct_actions.h`.
=> (Port to C++) popup menu for anchor image / emb file

future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_format.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_image.cc, future/src/ct/ct_image.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
- Finished popup menu actions for images
- Renamed  `get_tree_iter_from_node_id` to `get_node_from_node_id`, because every time I literately cannot find its name. 
I wonder how far away we are from making the program working? Maybe we can create some task list in #444 to visualize it?
=> (Port to C++) image popup menu

modules/config.py, modules/cons.py, modules/core.py
=> support mac osx to open file

modules/printing.py
I know it's minor fix, hopefully there's not something complex to do as there's no contributing.md
=> Corrected grammar in modules/printing.py (#344)

modules/core.py
Improve search in Command Palette feature.
=> Improve search in Command Palette, don't use SubSequence search

future/po/POTFILES.in
=> to fix #628  (missing data in pot file)

future/src/ct/ct_actions.h, future/src/ct/ct_actions_export.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_export.cc, future/src/ct/ct_export.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/tests/tests_misc_utils.cpp
=> (Port to C++) Export to HTML

future/src/ct/ct_actions_tree.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/tests/tests_misc_utils.cpp, modules/core.py
=> to add natural sorting for node sorting

modules/config.py
=> Recent document paths have wrong enconding

language-specs/go.lang, language-specs/groovy.lang, language-specs/javascript.lang, language-specs/kotlin.lang, language-specs/markdown.lang, language-specs/powershell.lang, language-specs/python3.lang, language-specs/rust.lang, language-specs/scala.lang, language-specs/yaml.lang
Hi, here:
- updates for some lang specs, taken from https://gitlab.gnome.org/GNOME/gtksourceview/tree/master/data/language-specs. I hope they are OK.
- new javascript.lang as a request from #228 
- also, issue   #92 can be closed because fulfilled
=> Updates for lang specs (#228, #92, #38)

future/src/ct/ct_actions.h, future/src/ct/ct_actions_export.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_export2txt.cc, future/src/ct/ct_export2txt.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h
=> (Port to C++) Export to TXT

modules/core.py, modules/pgsc_spellcheck.py, modules/support.py
Solves issue #592 
Triple clicking to select a paragraph like in word and other text editors was not a functionality, selecting a line on triple click seemed to be a default behavior. Added the handler for triple clicks.
=> Added triple click funtcionality to select paragraph

future/src/ct/ct_actions_edit.cc, modules/codeboxes.py
=> Resolves #655, Stay inside CodeBox after creation

modules/core.py
Resolved #677
File name was unicode and converting it to unicode threw an exception.
=> problem with opening another note

modules/core.py
=> Show node path in tooltip of Last Visited Nodes

glade/script3.js, modules/cons.py, modules/exports.py
=> redirect from an html page to index.html

modules/core.py
=> fix slow max_node_id()

modules/findreplace.py
Resolves #689
I tested a normal mode and regex in "Replace in Nodes Names", they should work OK.
=> fixes regex in "Replace in Nodes Names"

future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_find.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_export.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2txt.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
=> (Port to C+) Fixing some todo comments

future/src/ct/ct_actions.h, future/src/ct/ct_actions_file.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_state_machine.cc, future/src/ct/ct_treestore.cc
=> (Port to C++) node_delete, NodeTree shotcuts

modules/tablez.py
=> keep changed text in cell after table lost focus

modules/tablez.py
=> to fix Ctrl deselecting selected text in table cell on Win32

modules/menus.py
fixed https://github.com/giuspen/cherrytree/issues/305
=> Fixed https://github.com/giuspen/cherrytree/issues/305

future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_find.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_print.cc, future/src/ct/ct_print.h, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
I added label "Check on C++" on some pull requests to check them later.
=> (Port to C++) backport pygtk fixes; clipboard fixes

future/src/ct/ct_const.cc
A pretty simple one really, just to make powershell temp files save as "*.ps1" and add the code execution command to run them.
=> add powershell execution support

future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_state_machine.h, future/src/ct/ct_table.h
=> (Port to C++) last visited buttons in the header

future/src/ct/ct_actions_tree.cc, future/src/ct/ct_app.cc, future/src/ct/ct_config.cc, future/src/ct/ct_const.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_pref_dlg.cc
Fixed:
- grey cherry icon name
- switching left/right tree panel
- showing/hiding bookmark icon
- if config dir was missing, config file couldn't be created
- toolbar button size, so small buttons is really small
- with empty tree, text buffer should be readonly
=> (Port to C++) some fixes

locale/es.po
Corrected a few typos (locale/es.po)
=> Small fixes to Spanish translation

future/src/ct/ct_app.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h
=> (Port to C++) changes in Pref Dlg apply to all windows

future/README, future/configure.ac, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_format.cc, future/src/ct/ct_app.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_widgets.cc, future/src/ct/ct_widgets.h
you need to install gspell
- add gspell, updated README
- add word count
- fixes disabled toolbar
- add start on tray
- merge `config_apply_before_show_all` and `config_apply_after_show_all` into `config_apply`
=> (Port to C++) gspell & others

future/Makefile.am, future/src/ct/ct_actions.h, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_file.cc, future/src/ct/ct_actions_find.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_config.cc, future/src/ct/ct_const.cc, future/src/ct/ct_const.h, future/src/ct/ct_dialogs.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_menu.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_p7za_iface.cc, future/src/ct/ct_p7za_iface.h, future/src/ct/ct_pref_dlg.cc, future/src/ct/ct_pref_dlg.h, future/src/ct/ct_table.cc, future/src/ct/ct_treestore.cc, future/tests/tests_tmp_n_p7zip.cpp
=> (Port to C++) command palette, dialog about; 7z; icons; fixing layouts 

future/src/7za/CPP/Windows/FileDir.cpp, future/src/ct/ct_actions.h, future/src/ct/ct_actions_export.cc, future/src/ct/ct_actions_file.cc, future/src/ct/ct_app.cc, future/src/ct/ct_app.h, future/src/ct/ct_export2html.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_main_win.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h
There is only one issue, there is no code to copy css/js from GLADE
=> (Port to C++) export from cmd line

future/src/7za/CPP/7zip/Archive/7z/7zHandlerOut.cpp, future/src/7za/CPP/7zip/Archive/Tar/TarHandler.cpp, future/src/7za/CPP/7zip/UI/Common/ArchiveCommandLine.cpp, future/src/7za/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp, future/src/7za/CPP/7zip/UI/Common/OpenArchive.cpp, future/src/7za/CPP/Common/Wildcard.cpp, future/src/ct/CMakeLists.txt, future/src/ct/ct_actions_edit.cc, future/src/ct/ct_actions_others.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_codebox.cc, future/src/ct/ct_dialogs.h, future/src/ct/ct_imports.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_state_machine.h, future/src/ct/ct_treestore.cc
=> (Port to C++) fixed warnings for -Wall,- Wextra

snap/snapcraft.yaml
Added the common-id field for appstream usage.
=> Add common-id field for appstream

future/src/ct/ct_actions_tree.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
=> C++, drag and drop for nodes

future/CMakeLists.txt, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h
=> C++, fix 32bit compilation

future/src/ct/ct_storage_sqlite.cc
This one is on me
Turns out that widgets no longer save, because of course, the node is inserted before they are inserted and so the `has_*` field is never set :facepalm:, this was because I reordered the insertion order so as to abide by foreign key constraints
I have left the foreign keys in the schema as they are mostly for readability, but removed the pragma which enables them in every connection (and corrected the insertion order ofc).
=> Fix tables not saving with SQLite and remove enabling foreign keys

future/src/ct/ct_dialogs.cc
=> fixes UI freezing in search dialog

future/tests/data/ZimWiki/Home.txt, future/tests/data/ZimWiki/Home/Sub_of_home.txt, future/tests/data/ZimWiki/Home/Sub_of_home/Yet_another_sub.txt, future/tests/data/ZimWiki/notebook.zim
This adds the test data I used when testing the Zim parser
=> Added Zim wiki test data to tests/data

future/README.md
=> Spelling fix

future/src/ct/ct_md_parser.cc
=> Bugfix for complex md links

future/src/ct/ct_import_zim_handler.cc, future/src/ct/ct_imports.h, future/src/ct/ct_md_parser.cc, future/src/ct/ct_text_parser.cc
=> Fixed UB caused by capturing "this" in a static duration lambda

future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_menu.cc
Hi @giuspen, I added a new command to duplicate a node with subnodes.
For now, there is no proper image and title. Do you have any?
Resolves #872
Resolves #506
Resolves #501
Resolves #360
Resolves #318
=> command to duplicate node with subnodes

future/src/ct/ct_actions_import.cc, future/src/ct/ct_config.cc, future/src/ct/ct_main_win.cc
- apply config to textview
- fixes #845
- use dirImport for dialogs
=> applies textview config; fixes #845; use dirImport for dialogs

future/src/ct/ct_misc_utils.cc
=> fixes opening folder/file on win

future/src/ct/ct_actions_help.cc, future/src/ct/ct_imports.cc, future/src/ct/ct_imports.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_widgets.cc
- download image when image is copied from browser
- made a function to download stuff from the internet, sorry for the name
=> download image when image is copied from browser

future/src/ct/ct_dialogs.cc, future/src/ct/ct_main.cc
=> after repeated search, node is not selected

future/src/ct/ct_import_handler.cc, future/src/ct/ct_imports.h, future/src/ct/ct_parser.cc, future/src/ct/ct_text_parser.cc, future/src/ct/ct_types.h
=> Fix build errors on clang

future/src/ct/ct_import_zim_handler.cc, future/src/ct/ct_process.cc
=> fix mac build

future/src/ct/ct_actions_import.cc, future/src/ct/ct_export2html.cc, future/src/ct/ct_export2html.h, future/src/ct/ct_imports.cc, future/src/ct/ct_imports.h, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_p7za_iface.cc, future/tests/tests_misc_utils.cpp
=> Replace std::filesystem by glib

future/src/ct/ct_actions_import.cc
=> correct way to create imported buffer

future/src/ct/ct_actions_find.cc, future/src/ct/ct_dialogs.cc, future/src/ct/ct_pref_dlg.cc
=> fixes icons on win32

future/src/ct/ct_imports.cc
=> fixes text align from clipboard html

future/src/ct/ct_imports.cc
=> fixes copy/paste from VSCode (div as a text block)

future/src/ct/ct_actions.h, future/src/ct/ct_actions_others.cc, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_clipboard.cc, future/src/ct/ct_clipboard.h, future/src/ct/ct_menu.cc
Resolves #7
@giuspen , feel free to change menu item names and add icons :)
=> copy node link to clipboard; copy anchor link to clipboard

future/src/ct/ct_dialogs.cc
=> trimes off newliners from a node name

future/src/ct/ct_clipboard.cc, future/src/ct/ct_main_win.cc, future/src/ct/ct_misc_utils.cc, future/src/ct/ct_misc_utils.h, future/src/ct/ct_storage_xml.cc, future/src/ct/ct_storage_xml.h
=> xml parser can't parse some symbols so trim them off

future/src/ct/ct_dialogs.cc
=> addes double click to chose item in dlg

future/src/ct/ct_actions_edit.cc
=> allows user to add big files in sqlite

future/src/ct/ct_image.cc, modules/core.py
=> fixes not displaying names for attached files

future/src/ct/ct_dialogs.cc
=> fixes Help/About/weblink on KDE

future/src/ct/ct_main_win.cc
=> auto-save causes asking to save a new document on closing without discarding

future/src/ct/ct_parser_html.cc
=> fixes crash when html paste inserted an empty table

future/src/ct/ct_parser_html.cc
=> get back "disappeared" code

future/CMakeLists.txt, future/src/ct/ct_actions.h, future/src/ct/ct_actions_tree.cc, future/src/ct/ct_treestore.cc, future/src/ct/ct_treestore.h
Resolves #1050
Code worked fine on linux but caused crash on Win and MacOS.
=> check possibility of node drop to fix crash on win

future/src/ct/ct_main.cc
temporary work around for #1065
=> fixes issue with fallback font on Win32

future/src/ct/ct_actions.h, future/src/ct/ct_actions_find.cc
=> fixes search in widgets

future/src/ct/ct_main.cc
It's only for windows, other OS still don't have a log file
=> adds rotating log file for windows

src/ct/ct_filesystem.cc
=> logs error message if open_weblink fails on Win

src/ct/ct_parser_html.cc
=> parse style for <p> tag; find correct lightness for colors

src/ct/ct_export2html.cc, src/ct/ct_filesystem.cc, src/ct/ct_main.cc
Resolves #1090 
Removes log file on Win
=> fixes fs::copy/fs::move throwing exceptions

src/ct/ct_parser_html.cc
=> gets text aligment from html tag <p>

src/ct/ct_misc_utils.cc
=> xml_escape should use &#39; vs &apos;

src/ct/ct_actions_format.cc
=> restore cursor placement after applying tag

src/ct/ct_menu.cc
=> show special icon in recent docs if file is missing

src/ct/ct_actions_format.cc, src/ct/ct_dialogs.cc, src/ct/ct_dialogs.h, src/ct/ct_menu.cc
=> clear foreground/background color from dialog

src/ct/ct_state_machine.cc
=> fixes undo `nothing`

src/ct/ct_clipboard.cc, src/ct/ct_main_win.cc, src/ct/ct_state_machine.cc
=> resolves odd cursor jumps after undo; resolves minor issue with undo introduced after prev fix

src/ct/ct_app.cc
=> fixes 'reload_doc_last = false will not take effect'

src/ct/ct_config.cc, src/ct/ct_config.h, src/ct/ct_main_win.cc, src/ct/ct_pref_dlg.cc
Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line
=> adds scrolling beyond last line 

src/ct/ct_parser.cc
=> fixes leo file importing

src/ct/ct_app.cc, styles/Amy.xml
@giuspen , I added a new folder `styles` with one style. I checked a couple of styles from the link I gave, they work more or less.
=> adding new styles for gtksourceview

src/ct/ct_export2txt.cc, src/ct/ct_main_win.cc
=> fixes 'couldn't copy a link'

src/ct/ct_treestore.cc
=> removes invalid (deleted) anchor widgets from the list

src/ct/ct_parser_html.cc
=> fixes crash while importing from html due to odd attrs amount

src/ct/ct_actions_edit.cc, src/ct/ct_actions_find.cc, src/ct/ct_actions_tree.cc, src/ct/ct_main_win.cc, src/ct/ct_misc_utils.cc, src/ct/ct_misc_utils.h
=> str::time_format returns UTF-8

src/ct/ct_main_win.cc
=> ungray Paste popup item

src/ct/ct_app.cc
=> adds "--version" command option

src/ct/ct_export2html.cc
=> adds level into title class for html single export

src/ct/ct_app.cc
=> look up icons in user icon folder

src/ct/ct_filesystem.cc
=> uses ShellExecuteW to open links on Win

src/ct/ct_storage_xml.cc
=> supports huge xml files

src/ct/ct_export2pdf.cc, src/ct/ct_main_win.cc, src/ct/ct_parser_html.cc
=> adds fallback fonts on Win32

src/ct/ct_clipboard.cc
=> fixes paste on Apple

src/ct/ct_export2pdf.cc, src/ct/ct_export2pdf.h
=> fixes paragraph indent in pdf export

src/ct/ct_export2pdf.cc
=> scale-down anchor symbol in pdf export; draws a label for emb file icon in pdf export

src/ct/ct_actions_tree.cc
=> fixes freezing during deleting node

src/ct/ct_actions_tree.cc
=> fixes order for new created nodes

src/ct/ct_widgets.cc
=> fixes monospace zoom

src/ct/ct_actions_find.cc, src/ct/ct_dialogs.cc, src/ct/ct_dialogs.h
=> search dlg wasn't deleted after hiding

src/ct/ct_config.cc, src/ct/ct_main_win.cc, src/ct/ct_state_machine.h, src/ct/ct_types.h
=> restores visited nodes when file is opened

src/ct/ct_clipboard.cc, src/ct/ct_misc_utils.cc, src/ct/ct_misc_utils.h, src/ct/ct_storage_xml.cc
=> converts UTF with BOM into UTF-8

src/ct/ct_clipboard.cc, src/ct/ct_misc_utils.cc, src/ct/ct_misc_utils.h, src/ct/ct_storage_xml.cc
=> converts from any encoding to UTF-8

src/ct/ct_export2pdf.cc
=> pdf export supports white text

src/ct/ct_export2pdf.cc, src/ct/ct_export2pdf.h
=> compensates high dpi in MS print to pdf

src/ct/ct_parser_html.cc
Helps to fix https://github.com/giuspen/cherrytree/issues/1163#issuecomment-716863469
=> fixes pasting images with data:image/base64 format

src/ct/ct_storage_xml.cc, src/ct/ct_storage_xml.h, src/ct/ct_treestore.cc, src/ct/ct_treestore.h
=> fixes duplicated ids in xml document

src/ct/ct_parser_html.cc
=> fixes crash in html parser due to <li> without <ul>

src/ct/ct_imports.cc, src/ct/ct_imports.h, src/ct/ct_parser.cc, src/ct/ct_parser.h, src/ct/ct_parser_html.cc, src/ct/ct_storage_xml.cc, src/ct/ct_storage_xml.h, src/ct/ct_table.cc, src/ct/ct_table.h
Resolves #1342
PS converting tables into array of strings to save them into xml is not ideal, but I couldn't come with a better idea
=> table will contain right amount of column widths; removes table to xml copy-paste

src/ct/ct_p7za_iface.cc, src/ct/ct_p7za_iface.h, src/ct/ct_storage_control.cc, tests/tests_tmp_n_p7zip.cpp
=> suppress error when test a wrong password

src/ct/ct_dialogs.cc, src/ct/ct_storage_sqlite.cc, src/ct/ct_treestore.cc
=> Fixes not saving node props when only node props are changed

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md
Using a container to build can be useful if you're on Windows and/or want a self-contained build/debug environment.
=> Instructions to Build/Debug with VS Code container

src/ct/ct_dialogs.cc
=> fixes setting date in Gtk::Calendar

README.md
mention cherry is part of brew now
=> cherrytree is now included in homebrew

po/cherrytree.pot, po/ru.po
Fixed the Russian translation and added new lines for translation.
=> Modified ru.po (Add Korean) and cherrytree.pot (new lines add)

po/kk_KZ.po, po/ru.po
=> 100% ru.po and kk_KZ.po

src/ct/ct_dialogs_anch_widg.cc
Add Flip Image Functionality to the Image Properties Window. Useful feature that was missing.
=> Add Flip Image to Image Properties Window

snap/snapcraft.yaml
=> Add home plug

snap/snapcraft.yaml
=> Force turning off portal usage since it does not work on all distros

README.md
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>
=> Update Gentoo build instructions

snap/snapcraft.yaml
- Remove unnecessary libraries
- Add libxml2-utils dependency
- Set LD_LIBRARY_PATH without overwriting it
=> Snap updates needed for 1.0.0

debian/control, scripts/18.04/control, scripts/20.04/control, scripts/22.10/control
Adding new build dependencies to Debian/Ubuntu control files
> file
> libxml2-utils
=> Update Debian & Ubuntu control file with new build dependencies

po/kk_KZ.po, po/kk_LA.po, po/ru.po
=> 100% ru.po and kk_KZ.po and kk_LA.po

.github/ISSUE_TEMPLATE/bug_report.md
=> Fix typos in bug_report.md

src/ct/ct_dialogs_anch_widg.cc
Hi,
This adds the ability to select an area to crop to in the insert image dialogue.
You're obviously welcome to it as is, however:
1. I don't know if dumping a class into a source file like that is the done thing in C++, should it be declared in a header?  I've never worked on a C++ project big enough for that sort of thing to matter!
2. There's currently no indication in the UI that this feature is there or how it relates to the width and height options.  (At the moment, the whole image is scaled according to the width and height values, then cropped according to the selection.)  I'm not sure what the best way to do the UI would be now.
3. I'm still having `load_image_into_dialog` create the preview pixbuf at whatever resolution it sees fit. It then hands that to the `CropImage` widget …
=> Add cropping to insert image dialogue
